file(GLOB shader_files RELATIVE "${INPUT_DIR}" "${INPUT_DIR}/*.bin")
list(LENGTH shader_files input_count)
if(input_count LESS 1)
    message(FATAL_ERROR "No input shaders found")
endif()

set(input_hashes)
foreach(filename IN LISTS shader_files)
    get_filename_component(hash "${filename}" NAME_WE)
    string(LENGTH "${hash}" hash_length)
    if(NOT hash_length EQUAL 16 OR NOT hash MATCHES "^[0-9A-Fa-f]+$")
        message(FATAL_ERROR "Input is not named by a 16-digit hash: ${filename}")
    endif()
    string(TOUPPER "${hash}" hash)
    list(APPEND input_hashes "${hash}")
endforeach()
list(REMOVE_DUPLICATES input_hashes)
list(LENGTH input_hashes unique_input_count)
if(NOT unique_input_count EQUAL input_count)
    message(FATAL_ERROR "Input shader hashes are not unique")
endif()
list(SORT input_hashes)

file(STRINGS "${CACHE}" entry_lines REGEX "^[ \t]*\\{ 0x")
list(LENGTH entry_lines entry_count)
# A shader XenosRecomp could not translate is left out of the cache (it just
# misses at runtime), so the entries are a non-empty subset of the inputs.
if(entry_count LESS 1 OR entry_count GREATER input_count)
    message(FATAL_ERROR "Expected 1..${input_count} cache entries, found ${entry_count}")
endif()
if(NOT entry_count EQUAL input_count)
    math(EXPR skipped "${input_count} - ${entry_count}")
    message(WARNING "${skipped} of ${input_count} input shaders are missing from the cache")
endif()

set(output_hashes)
set(expected_dxil_offset 0)
set(expected_spirv_offset 0)
foreach(line IN LISTS entry_lines)
    if(NOT line MATCHES "\\{ 0x([0-9A-F]+), ([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+), \"([^\"]+)\" \\},")
        message(FATAL_ERROR "Malformed cache entry: ${line}")
    endif()
    set(hash "${CMAKE_MATCH_1}")
    string(LENGTH "${hash}" hash_length)
    if(hash_length GREATER 16)
        message(FATAL_ERROR "Cache entry hash is wider than 64 bits: ${hash}")
    endif()
    while(hash_length LESS 16)
        string(PREPEND hash "0")
        math(EXPR hash_length "${hash_length} + 1")
    endwhile()
    set(dxil_offset "${CMAKE_MATCH_2}")
    set(dxil_size "${CMAKE_MATCH_3}")
    set(spirv_offset "${CMAKE_MATCH_4}")
    set(spirv_size "${CMAKE_MATCH_5}")
    set(filename "${CMAKE_MATCH_9}")

    if(NOT filename STREQUAL "shaders/${hash}.bin")
        message(FATAL_ERROR "Cache filename/hash mismatch: ${filename} vs ${hash}")
    endif()
    if(dxil_size EQUAL 0 OR spirv_size EQUAL 0)
        message(FATAL_ERROR "Cache entry ${hash} has an empty DXIL or SPIR-V range")
    endif()
    if(NOT dxil_offset EQUAL expected_dxil_offset OR
       NOT spirv_offset EQUAL expected_spirv_offset)
        message(FATAL_ERROR "Cache entry ${hash} has a non-contiguous shader range")
    endif()
    math(EXPR expected_dxil_offset "${dxil_offset} + ${dxil_size}")
    math(EXPR expected_spirv_offset "${spirv_offset} + ${spirv_size}")
    list(APPEND output_hashes "${hash}")
endforeach()

set(unique_output_hashes ${output_hashes})
list(REMOVE_DUPLICATES unique_output_hashes)
list(LENGTH unique_output_hashes unique_output_count)
if(NOT unique_output_count EQUAL entry_count)
    message(FATAL_ERROR "Generated cache hashes are not unique")
endif()
set(sorted_output_hashes ${output_hashes})
list(SORT sorted_output_hashes)
if(NOT output_hashes STREQUAL sorted_output_hashes)
    message(FATAL_ERROR "Generated cache hashes are not in sorted order")
endif()
foreach(hash IN LISTS output_hashes)
    list(FIND input_hashes "${hash}" input_index)
    if(input_index EQUAL -1)
        message(FATAL_ERROR "Generated cache contains a shader that is not an input: ${hash}")
    endif()
endforeach()

file(READ "${CACHE}" cache_contents)
if(NOT cache_contents MATCHES "const size_t g_dxilCacheDecompressedSize = ([0-9]+);")
    message(FATAL_ERROR "DXIL decompressed size declaration is missing")
endif()
set(dxil_total "${CMAKE_MATCH_1}")
if(NOT cache_contents MATCHES "const size_t g_spirvCacheDecompressedSize = ([0-9]+);")
    message(FATAL_ERROR "SPIR-V decompressed size declaration is missing")
endif()
set(spirv_total "${CMAKE_MATCH_1}")
if(NOT dxil_total EQUAL expected_dxil_offset)
    message(FATAL_ERROR "DXIL ranges do not match the declared decompressed size")
endif()
if(NOT spirv_total EQUAL expected_spirv_offset)
    message(FATAL_ERROR "SPIR-V ranges do not match the declared decompressed size")
endif()

message("Verified ${entry_count} sorted unique shaders with matching filenames and valid DXIL/SPIR-V ranges")
